export const options = {
  colors: ['#ffffff'],
  deterministic: false,
  enableOptimizations: true,
  enableTooltip: false,
  fontFamily: 'TitilliumWeb',
  fontSizes: [24, 48],
  fontStyle: 'normal',
  fontWeight: 'normal',
  padding: 1,
  rotations: 2,
  rotationAngles: [0, 90],
  scale: 'linear',
  spiral: 'rectangular',
  transitionDuration: 3000,
};

export const mobileOptions = {
  colors: ['#ffffff'],
  deterministic: true,
  enableTooltip: false,
  fontFamily: 'TitilliumWeb',
  fontSizes: [20, 40],
  fontStyle: 'normal',
  fontWeight: 'normal',
  padding: 1,
  rotations: 1,
  rotationAngles: [0, 90],
  scale: 'sqrt',
  spiral: 'rectangular',
  transitionDuration: 3000,
};
